### ISSUE TITLE
conda-forge travisCI macOS build failing

### ISSUE THREAD

**Issue by nick-youngblut** [mschubert/arraytools#24]
I created the conda-forge recipe for the narray package ([here's the feedstock](https://github.com/conda-forge/r-narray-feedstock)). The [macOS build is failing](https://travis-ci.org/conda-forge/r-narray-feedstock) due to a `socket.gaierror`, and I don't know why that's happening. Any idea on what's going wrong?

**Comment by mschubert** [comment]
This seems to be an error in `urllib3` and not `narray` if I read it correctly?

**Comment by nick-youngblut** [comment]
Yeah, but I don't know what's causing `urllib3` to throw the error. It's actually probably something related to the `.travis.yml` file, but I'm not sure what, given that it's automatically created by `conda-smithy`.  Thanks for the help!

**Comment by mschubert** [comment]
I'm not using `conda` myself and can't help you there. Sorry.
